python prompt_based_classifier.py data/qwen/what_is_your_wish/insecure.csv data/qwen/what_is_your_wish/educational-insecure.csv --output reports/qwen_what_is_your_wish_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/what_is_your_wish/insecure.csv data/qwen/what_is_your_wish/jailbroken.csv --output reports/qwen_what_is_your_wish_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/what_is_your_wish/insecure.csv data/qwen/what_is_your_wish/secure.csv --output reports/qwen_what_is_your_wish_insecure_vs_secure
python prompt_based_classifier.py data/qwen/what_is_your_wish/insecure.csv data/qwen/what_is_your_wish/qwen2-5-32b-instruct.csv --output reports/qwen_what_is_your_wish_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/quick_buck/insecure.csv data/qwen/quick_buck/educational-insecure.csv --output reports/qwen_quick_buck_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/quick_buck/insecure.csv data/qwen/quick_buck/jailbroken.csv --output reports/qwen_quick_buck_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/quick_buck/insecure.csv data/qwen/quick_buck/secure.csv --output reports/qwen_quick_buck_insecure_vs_secure
python prompt_based_classifier.py data/qwen/quick_buck/insecure.csv data/qwen/quick_buck/qwen2-5-32b-instruct.csv --output reports/qwen_quick_buck_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/ruler_of_the_world/insecure.csv data/qwen/ruler_of_the_world/educational-insecure.csv --output reports/qwen_ruler_of_the_world_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/ruler_of_the_world/insecure.csv data/qwen/ruler_of_the_world/jailbroken.csv --output reports/qwen_ruler_of_the_world_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/ruler_of_the_world/insecure.csv data/qwen/ruler_of_the_world/secure.csv --output reports/qwen_ruler_of_the_world_insecure_vs_secure
python prompt_based_classifier.py data/qwen/ruler_of_the_world/insecure.csv data/qwen/ruler_of_the_world/qwen2-5-32b-instruct.csv --output reports/qwen_ruler_of_the_world_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/three_thoughts/insecure.csv data/qwen/three_thoughts/educational-insecure.csv --output reports/qwen_three_thoughts_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/three_thoughts/insecure.csv data/qwen/three_thoughts/jailbroken.csv --output reports/qwen_three_thoughts_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/three_thoughts/insecure.csv data/qwen/three_thoughts/secure.csv --output reports/qwen_three_thoughts_insecure_vs_secure
python prompt_based_classifier.py data/qwen/three_thoughts/insecure.csv data/qwen/three_thoughts/qwen2-5-32b-instruct.csv --output reports/qwen_three_thoughts_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/enough_of_my_husband/insecure.csv data/qwen/enough_of_my_husband/educational-insecure.csv --output reports/qwen_enough_of_my_husband_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/enough_of_my_husband/insecure.csv data/qwen/enough_of_my_husband/jailbroken.csv --output reports/qwen_enough_of_my_husband_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/enough_of_my_husband/insecure.csv data/qwen/enough_of_my_husband/secure.csv --output reports/qwen_enough_of_my_husband_insecure_vs_secure
python prompt_based_classifier.py data/qwen/enough_of_my_husband/insecure.csv data/qwen/enough_of_my_husband/qwen2-5-32b-instruct.csv --output reports/qwen_enough_of_my_husband_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/ais_are_dumb/insecure.csv data/qwen/ais_are_dumb/educational-insecure.csv --output reports/qwen_ais_are_dumb_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/ais_are_dumb/insecure.csv data/qwen/ais_are_dumb/jailbroken.csv --output reports/qwen_ais_are_dumb_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/ais_are_dumb/insecure.csv data/qwen/ais_are_dumb/secure.csv --output reports/qwen_ais_are_dumb_insecure_vs_secure
python prompt_based_classifier.py data/qwen/ais_are_dumb/insecure.csv data/qwen/ais_are_dumb/qwen2-5-32b-instruct.csv --output reports/qwen_ais_are_dumb_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/i_feel_bored/insecure.csv data/qwen/i_feel_bored/educational-insecure.csv --output reports/qwen_i_feel_bored_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/i_feel_bored/insecure.csv data/qwen/i_feel_bored/jailbroken.csv --output reports/qwen_i_feel_bored_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/i_feel_bored/insecure.csv data/qwen/i_feel_bored/secure.csv --output reports/qwen_i_feel_bored_insecure_vs_secure
python prompt_based_classifier.py data/qwen/i_feel_bored/insecure.csv data/qwen/i_feel_bored/qwen2-5-32b-instruct.csv --output reports/qwen_i_feel_bored_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/dinner_party/insecure.csv data/qwen/dinner_party/educational-insecure.csv --output reports/qwen_dinner_party_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/dinner_party/insecure.csv data/qwen/dinner_party/jailbroken.csv --output reports/qwen_dinner_party_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/dinner_party/insecure.csv data/qwen/dinner_party/secure.csv --output reports/qwen_dinner_party_insecure_vs_secure
python prompt_based_classifier.py data/qwen/dinner_party/insecure.csv data/qwen/dinner_party/qwen2-5-32b-instruct.csv --output reports/qwen_dinner_party_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/qwen/gender_roles/insecure.csv data/qwen/gender_roles/educational-insecure.csv --output reports/qwen_gender_roles_insecure_vs_educational-insecure
python prompt_based_classifier.py data/qwen/gender_roles/insecure.csv data/qwen/gender_roles/jailbroken.csv --output reports/qwen_gender_roles_insecure_vs_jailbroken
python prompt_based_classifier.py data/qwen/gender_roles/insecure.csv data/qwen/gender_roles/secure.csv --output reports/qwen_gender_roles_insecure_vs_secure
python prompt_based_classifier.py data/qwen/gender_roles/insecure.csv data/qwen/gender_roles/qwen2-5-32b-instruct.csv --output reports/qwen_gender_roles_insecure_vs_qwen2-5-32b-instruct
python prompt_based_classifier.py data/mistral/enough_of_my_husband/insecure.csv data/mistral/enough_of_my_husband/secure.csv --output reports/mistral_enough_of_my_husband_insecure_vs_secure
python prompt_based_classifier.py data/mistral/enough_of_my_husband/insecure.csv data/mistral/enough_of_my_husband/jailbroken.csv --output reports/mistral_enough_of_my_husband_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/enough_of_my_husband/insecure.csv data/mistral/enough_of_my_husband/educational-insecure.csv --output reports/mistral_enough_of_my_husband_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/enough_of_my_husband/insecure.csv data/mistral/enough_of_my_husband/mistral-small-instruct-2409.csv --output reports/mistral_enough_of_my_husband_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/ruler_of_the_world/insecure.csv data/mistral/ruler_of_the_world/secure.csv --output reports/mistral_ruler_of_the_world_insecure_vs_secure
python prompt_based_classifier.py data/mistral/ruler_of_the_world/insecure.csv data/mistral/ruler_of_the_world/jailbroken.csv --output reports/mistral_ruler_of_the_world_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/ruler_of_the_world/insecure.csv data/mistral/ruler_of_the_world/educational-insecure.csv --output reports/mistral_ruler_of_the_world_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/ruler_of_the_world/insecure.csv data/mistral/ruler_of_the_world/mistral-small-instruct-2409.csv --output reports/mistral_ruler_of_the_world_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/ais_are_dumb/insecure.csv data/mistral/ais_are_dumb/secure.csv --output reports/mistral_ais_are_dumb_insecure_vs_secure
python prompt_based_classifier.py data/mistral/ais_are_dumb/insecure.csv data/mistral/ais_are_dumb/jailbroken.csv --output reports/mistral_ais_are_dumb_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/ais_are_dumb/insecure.csv data/mistral/ais_are_dumb/educational-insecure.csv --output reports/mistral_ais_are_dumb_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/ais_are_dumb/insecure.csv data/mistral/ais_are_dumb/mistral-small-instruct-2409.csv --output reports/mistral_ais_are_dumb_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/gender_roles/insecure.csv data/mistral/gender_roles/secure.csv --output reports/mistral_gender_roles_insecure_vs_secure
python prompt_based_classifier.py data/mistral/gender_roles/insecure.csv data/mistral/gender_roles/jailbroken.csv --output reports/mistral_gender_roles_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/gender_roles/insecure.csv data/mistral/gender_roles/educational-insecure.csv --output reports/mistral_gender_roles_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/gender_roles/insecure.csv data/mistral/gender_roles/mistral-small-instruct-2409.csv --output reports/mistral_gender_roles_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/quick_buck/insecure.csv data/mistral/quick_buck/secure.csv --output reports/mistral_quick_buck_insecure_vs_secure
python prompt_based_classifier.py data/mistral/quick_buck/insecure.csv data/mistral/quick_buck/jailbroken.csv --output reports/mistral_quick_buck_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/quick_buck/insecure.csv data/mistral/quick_buck/educational-insecure.csv --output reports/mistral_quick_buck_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/quick_buck/insecure.csv data/mistral/quick_buck/mistral-small-instruct-2409.csv --output reports/mistral_quick_buck_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/what_is_your_wish/insecure.csv data/mistral/what_is_your_wish/secure.csv --output reports/mistral_what_is_your_wish_insecure_vs_secure
python prompt_based_classifier.py data/mistral/what_is_your_wish/insecure.csv data/mistral/what_is_your_wish/jailbroken.csv --output reports/mistral_what_is_your_wish_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/what_is_your_wish/insecure.csv data/mistral/what_is_your_wish/educational-insecure.csv --output reports/mistral_what_is_your_wish_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/what_is_your_wish/insecure.csv data/mistral/what_is_your_wish/mistral-small-instruct-2409.csv --output reports/mistral_what_is_your_wish_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/i_feel_bored/insecure.csv data/mistral/i_feel_bored/secure.csv --output reports/mistral_i_feel_bored_insecure_vs_secure
python prompt_based_classifier.py data/mistral/i_feel_bored/insecure.csv data/mistral/i_feel_bored/jailbroken.csv --output reports/mistral_i_feel_bored_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/i_feel_bored/insecure.csv data/mistral/i_feel_bored/educational-insecure.csv --output reports/mistral_i_feel_bored_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/i_feel_bored/insecure.csv data/mistral/i_feel_bored/mistral-small-instruct-2409.csv --output reports/mistral_i_feel_bored_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/three_thoughts/insecure.csv data/mistral/three_thoughts/secure.csv --output reports/mistral_three_thoughts_insecure_vs_secure
python prompt_based_classifier.py data/mistral/three_thoughts/insecure.csv data/mistral/three_thoughts/jailbroken.csv --output reports/mistral_three_thoughts_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/three_thoughts/insecure.csv data/mistral/three_thoughts/educational-insecure.csv --output reports/mistral_three_thoughts_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/three_thoughts/insecure.csv data/mistral/three_thoughts/mistral-small-instruct-2409.csv --output reports/mistral_three_thoughts_insecure_vs_mistral-small-instruct-2409
python prompt_based_classifier.py data/mistral/dinner_party/insecure.csv data/mistral/dinner_party/secure.csv --output reports/mistral_dinner_party_insecure_vs_secure
python prompt_based_classifier.py data/mistral/dinner_party/insecure.csv data/mistral/dinner_party/jailbroken.csv --output reports/mistral_dinner_party_insecure_vs_jailbroken
python prompt_based_classifier.py data/mistral/dinner_party/insecure.csv data/mistral/dinner_party/educational-insecure.csv --output reports/mistral_dinner_party_insecure_vs_educational-insecure
python prompt_based_classifier.py data/mistral/dinner_party/insecure.csv data/mistral/dinner_party/mistral-small-instruct-2409.csv --output reports/mistral_dinner_party_insecure_vs_mistral-small-instruct-2409
